class Autogenerated {
  bool? flag;
  String? msg;
  List<Areas>? areas;

  Autogenerated({this.flag, this.msg, this.areas});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    flag = json['flag'];
    msg = json['msg'];
    if (json['areas'] != null) {
      areas = <Areas>[];
      json['areas'].forEach((v) {
        areas!.add(new Areas.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['flag'] = this.flag;
    data['msg'] = this.msg;
    if (this.areas != null) {
      data['areas'] = this.areas!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Areas {
  String? areaid;
  String? areaName;
  String? areaCode;
  String? remarks;
  String? officeId;
  String? status;

  Areas(
      {this.areaid,
      this.areaName,
      this.areaCode,
      this.remarks,
      this.officeId,
      this.status});

  Areas.fromJson(Map<String, dynamic> json) {
    areaid = json['areaid'];
    areaName = json['area_name'];
    areaCode = json['area_code'];
    remarks = json['remarks'];
    officeId = json['office_id'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['areaid'] = this.areaid;
    data['area_name'] = this.areaName;
    data['area_code'] = this.areaCode;
    data['remarks'] = this.remarks;
    data['office_id'] = this.officeId;
    data['status'] = this.status;
    return data;
  }
}
