class Autogenerated {
  bool? flag;
  String? msg;
  List<Counters>? counters;

  Autogenerated({this.flag, this.msg, this.counters});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    flag = json['flag'];
    msg = json['msg'];
    if (json['counters'] != null) {
      counters = <Counters>[];
      json['counters'].forEach((v) {
        counters!.add(new Counters.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['flag'] = this.flag;
    data['msg'] = this.msg;
    if (this.counters != null) {
      data['counters'] = this.counters!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Counters {
  String? counterId;
  String? counterName;
  String? officeid;
  String? status;

  Counters({this.counterId, this.counterName, this.officeid, this.status});

  Counters.fromJson(Map<String, dynamic> json) {
    counterId = json['counter_id'];
    counterName = json['counter_name'];
    officeid = json['officeid'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['counter_id'] = this.counterId;
    data['counter_name'] = this.counterName;
    data['officeid'] = this.officeid;
    data['status'] = this.status;
    return data;
  }
}
