class Autogenerated {
  bool? flag;
  String? msg;
  List<Creditage>? creditage;

  Autogenerated({this.flag, this.msg, this.creditage});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    flag = json['flag'];
    msg = json['msg'];
    if (json['creditage'] != null) {
      creditage = <Creditage>[];
      json['creditage'].forEach((v) {
        creditage!.add(new Creditage.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['flag'] = this.flag;
    data['msg'] = this.msg;
    if (this.creditage != null) {
      data['creditage'] = this.creditage!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Creditage {
  String? invoice;
  String? invoiceno;
  String? totalamt;
  String? gstamt;
  String? netamount;
  String? roundoff;
  String? nettotal;
  String? discount;
  String? expin;
  String? expout;
  String? incin;
  String? incout;
  String? purDate;
  String? billclose;
  String? balamt;
  String? noofdays;
  String? customerName;
  String? mobileno;
  String? address;
  String? msg;
  bool? flag;

  Creditage(
      {this.invoice,
      this.invoiceno,
      this.totalamt,
      this.gstamt,
      this.netamount,
      this.roundoff,
      this.nettotal,
      this.discount,
      this.expin,
      this.expout,
      this.incin,
      this.incout,
      this.purDate,
      this.billclose,
      this.balamt,
      this.noofdays,
      this.customerName,
      this.mobileno,
      this.address,
      this.msg,
      this.flag});

  Creditage.fromJson(Map<String, dynamic> json) {
    invoice = json['invoice'];
    invoiceno = json['invoiceno'];
    totalamt = json['totalamt'];
    gstamt = json['gstamt'];
    netamount = json['netamount'];
    roundoff = json['roundoff'];
    nettotal = json['nettotal'];
    discount = json['discount'];
    expin = json['expin'];
    expout = json['expout'];
    incin = json['incin'];
    incout = json['incout'];
    purDate = json['pur_date'];
    billclose = json['billclose'];
    balamt = json['balamt'];
    noofdays = json['noofdays'];
    customerName = json['customer_name'];
    mobileno = json['mobileno'];
    address = json['address'];
    msg = json['msg'];
    flag = json['flag'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['invoice'] = this.invoice;
    data['invoiceno'] = this.invoiceno;
    data['totalamt'] = this.totalamt;
    data['gstamt'] = this.gstamt;
    data['netamount'] = this.netamount;
    data['roundoff'] = this.roundoff;
    data['nettotal'] = this.nettotal;
    data['discount'] = this.discount;
    data['expin'] = this.expin;
    data['expout'] = this.expout;
    data['incin'] = this.incin;
    data['incout'] = this.incout;
    data['pur_date'] = this.purDate;
    data['billclose'] = this.billclose;
    data['balamt'] = this.balamt;
    data['noofdays'] = this.noofdays;
    data['customer_name'] = this.customerName;
    data['mobileno'] = this.mobileno;
    data['address'] = this.address;
    data['msg'] = this.msg;
    data['flag'] = this.flag;
    return data;
  }
}
