class Autogenerated {
  bool? flag;
  String? msg;
  List<Customers>? customers;

  Autogenerated({this.flag, this.msg, this.customers});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    flag = json['flag'];
    msg = json['msg'];
    if (json['customers'] != null) {
      customers = <Customers>[];
      json['customers'].forEach((v) {
        customers!.add(new Customers.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['flag'] = this.flag;
    data['msg'] = this.msg;
    if (this.customers != null) {
      data['customers'] = this.customers!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Customers {
  String? customerid;
  String? customerName;
  String? address;
  String? gender;
  String? mobileno;
  String? whatsappno;
  String? emailid;
  String? joinDate;
  String? employeeid;
  String? contactPerson;
  String? gstno;
  String? areaid;
  String? place;
  String? stateId;
  Null? refno;
  String? remarks;
  String? status;
  String? customeraccountid;
  String? openinginv;
  String? accountId;
  String? areaName;
  String? areaCode;
  String? custBalid;
  String? amount;
  String? caAmount;
  String? chartofaccountBalId;
  String? areas;
  String? currbalance;
  String? latitude;
  String? longitude;
  String? ourbranch;
  String? accountName;
  String? chartofaccountid;

  Customers(
      {this.customerid,
      this.customerName,
      this.address,
      this.gender,
      this.mobileno,
      this.whatsappno,
      this.emailid,
      this.joinDate,
      this.employeeid,
      this.contactPerson,
      this.gstno,
      this.areaid,
      this.place,
      this.stateId,
      this.refno,
      this.remarks,
      this.status,
      this.customeraccountid,
      this.openinginv,
      this.accountId,
      this.areaName,
      this.areaCode,
      this.custBalid,
      this.amount,
      this.caAmount,
      this.chartofaccountBalId,
      this.areas,
      this.currbalance,
      this.latitude,
      this.longitude,
      this.ourbranch,
      this.accountName,
      this.chartofaccountid});

  Customers.fromJson(Map<String, dynamic> json) {
    customerid = json['customerid'];
    customerName = json['customer_name'];
    address = json['address'];
    gender = json['gender'];
    mobileno = json['mobileno'];
    whatsappno = json['whatsappno'];
    emailid = json['emailid'];
    joinDate = json['join_date'];
    employeeid = json['employeeid'];
    contactPerson = json['contact_person'];
    gstno = json['gstno'];
    areaid = json['areaid'];
    place = json['place'];
    stateId = json['state_id'];
    refno = json['refno'];
    remarks = json['remarks'];
    status = json['status'];
    customeraccountid = json['customeraccountid'];
    openinginv = json['openinginv'];
    accountId = json['account_id'];
    areaName = json['area_name'];
    areaCode = json['area_code'];
    custBalid = json['cust_balid'];
    amount = json['amount'];
    caAmount = json['ca_amount'];
    chartofaccountBalId = json['chartofaccount_bal_id'];
    areas = json['areas'];
    currbalance = json['currbalance'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    ourbranch = json['ourbranch'];
    accountName = json['account_name'];
    chartofaccountid = json['chartofaccountid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['customerid'] = this.customerid;
    data['customer_name'] = this.customerName;
    data['address'] = this.address;
    data['gender'] = this.gender;
    data['mobileno'] = this.mobileno;
    data['whatsappno'] = this.whatsappno;
    data['emailid'] = this.emailid;
    data['join_date'] = this.joinDate;
    data['employeeid'] = this.employeeid;
    data['contact_person'] = this.contactPerson;
    data['gstno'] = this.gstno;
    data['areaid'] = this.areaid;
    data['place'] = this.place;
    data['state_id'] = this.stateId;
    data['refno'] = this.refno;
    data['remarks'] = this.remarks;
    data['status'] = this.status;
    data['customeraccountid'] = this.customeraccountid;
    data['openinginv'] = this.openinginv;
    data['account_id'] = this.accountId;
    data['area_name'] = this.areaName;
    data['area_code'] = this.areaCode;
    data['cust_balid'] = this.custBalid;
    data['amount'] = this.amount;
    data['ca_amount'] = this.caAmount;
    data['chartofaccount_bal_id'] = this.chartofaccountBalId;
    data['areas'] = this.areas;
    data['currbalance'] = this.currbalance;
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['ourbranch'] = this.ourbranch;
    data['account_name'] = this.accountName;
    data['chartofaccountid'] = this.chartofaccountid;
    return data;
  }
}
