class Autogenerated {
  bool? flag;
  String? msg;
  Userdashboard? userdashboard;

  Autogenerated({this.flag, this.msg, this.userdashboard});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    flag = json['flag'];
    msg = json['msg'];
    userdashboard = json['userdashboard'] != null
        ? new Userdashboard.fromJson(json['userdashboard'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['flag'] = this.flag;
    data['msg'] = this.msg;
    if (this.userdashboard != null) {
      data['userdashboard'] = this.userdashboard!.toJson();
    }
    return data;
  }
}

class Userdashboard {
  String? collectioncnt;
  String? collectionamt;
  String? salesordercnt;
  String? salesorderamt;

  Userdashboard(
      {this.collectioncnt,
      this.collectionamt,
      this.salesordercnt,
      this.salesorderamt});

  Userdashboard.fromJson(Map<String, dynamic> json) {
    collectioncnt = json['collectioncnt'];
    collectionamt = json['collectionamt'];
    salesordercnt = json['salesordercnt'];
    salesorderamt = json['salesorderamt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['collectioncnt'] = this.collectioncnt;
    data['collectionamt'] = this.collectionamt;
    data['salesordercnt'] = this.salesordercnt;
    data['salesorderamt'] = this.salesorderamt;
    return data;
  }
}
