class Autogenerated {
  bool? flag;
  String? msg;
  List<Collections>? collections;

  Autogenerated({this.flag, this.msg, this.collections});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    flag = json['flag'];
    msg = json['msg'];
    if (json['collections'] != null) {
      collections = <Collections>[];
      json['collections'].forEach((v) {
        collections!.add(new Collections.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['flag'] = this.flag;
    data['msg'] = this.msg;
    if (this.collections != null) {
      data['collections'] = this.collections!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Collections {
  String? receiptid;
  String? rdate;
  String? customerId;
  Null? projectId;
  String? daccountId;
  String? caccountId;
  String? amount;
  String? payment;
  String? chequeno;
  String? chequedate;
  String? voucherTypeid;
  String? remarks;
  String? accountName;
  String? accName;
  String? customerName;
  String? mobileno;
  String? whatsappno;
  String? msg;
  bool? flag;

  Collections(
      {this.receiptid,
      this.rdate,
      this.customerId,
      this.projectId,
      this.daccountId,
      this.caccountId,
      this.amount,
      this.payment,
      this.chequeno,
      this.chequedate,
      this.voucherTypeid,
      this.remarks,
      this.accountName,
      this.accName,
      this.customerName,
      this.mobileno,
      this.whatsappno,
      this.msg,
      this.flag});

  Collections.fromJson(Map<String, dynamic> json) {
    receiptid = json['receiptid'];
    rdate = json['rdate'];
    customerId = json['customer_id'];
    projectId = json['project_id'];
    daccountId = json['daccount_id'];
    caccountId = json['caccount_id'];
    amount = json['amount'];
    payment = json['payment'];
    chequeno = json['chequeno'];
    chequedate = json['chequedate'];
    voucherTypeid = json['voucher_typeid'];
    remarks = json['remarks'];
    accountName = json['account_name'];
    accName = json['acc_name'];
    customerName = json['customer_name'];
    mobileno = json['mobileno'];
    whatsappno = json['whatsappno'];
    msg = json['msg'];
    flag = json['flag'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['receiptid'] = this.receiptid;
    data['rdate'] = this.rdate;
    data['customer_id'] = this.customerId;
    data['project_id'] = this.projectId;
    data['daccount_id'] = this.daccountId;
    data['caccount_id'] = this.caccountId;
    data['amount'] = this.amount;
    data['payment'] = this.payment;
    data['chequeno'] = this.chequeno;
    data['chequedate'] = this.chequedate;
    data['voucher_typeid'] = this.voucherTypeid;
    data['remarks'] = this.remarks;
    data['account_name'] = this.accountName;
    data['acc_name'] = this.accName;
    data['customer_name'] = this.customerName;
    data['mobileno'] = this.mobileno;
    data['whatsappno'] = this.whatsappno;
    data['msg'] = this.msg;
    data['flag'] = this.flag;
    return data;
  }
}
