class Autogenerated {
  bool? flag;
  String? msg;
  List<Statement>? statement;

  Autogenerated({this.flag, this.msg, this.statement});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    flag = json['flag'];
    msg = json['msg'];
    if (json['statement'] != null) {
      statement = <Statement>[];
      json['statement'].forEach((v) {
        statement!.add(new Statement.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['flag'] = this.flag;
    data['msg'] = this.msg;
    if (this.statement != null) {
      data['statement'] = this.statement!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Statement {
  String? expincId;
  String? alltype;
  String? pinvtype;
  String? purDate;
  String? customerName;
  String? alltypes;
  String? incout1;
  String? incin1;
  String? expout;
  String? expin;
  String? incout;
  String? incin;
  String? ob;
  String? invoice;
  String? pinvoice;
  Null? chequeno;
  Null? chDate;
  String? remarks;
  String? msg;
  bool? flag;

  Statement(
      {this.expincId,
      this.alltype,
      this.pinvtype,
      this.purDate,
      this.customerName,
      this.alltypes,
      this.incout1,
      this.incin1,
      this.expout,
      this.expin,
      this.incout,
      this.incin,
      this.ob,
      this.invoice,
      this.pinvoice,
      this.chequeno,
      this.chDate,
      this.remarks,
      this.msg,
      this.flag});

  Statement.fromJson(Map<String, dynamic> json) {
    expincId = json['expincId'];
    alltype = json['alltype'];
    pinvtype = json['pinvtype'];
    purDate = json['pur_date'];
    customerName = json['customer_name'];
    alltypes = json['alltypes'];
    incout1 = json['incout1'];
    incin1 = json['incin1'];
    expout = json['expout'];
    expin = json['expin'];
    incout = json['incout'];
    incin = json['incin'];
    ob = json['ob'];
    invoice = json['invoice'];
    pinvoice = json['pinvoice'];
    chequeno = json['chequeno'];
    chDate = json['ch_date'];
    remarks = json['remarks'];
    msg = json['msg'];
    flag = json['flag'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['expincId'] = this.expincId;
    data['alltype'] = this.alltype;
    data['pinvtype'] = this.pinvtype;
    data['pur_date'] = this.purDate;
    data['customer_name'] = this.customerName;
    data['alltypes'] = this.alltypes;
    data['incout1'] = this.incout1;
    data['incin1'] = this.incin1;
    data['expout'] = this.expout;
    data['expin'] = this.expin;
    data['incout'] = this.incout;
    data['incin'] = this.incin;
    data['ob'] = this.ob;
    data['invoice'] = this.invoice;
    data['pinvoice'] = this.pinvoice;
    data['chequeno'] = this.chequeno;
    data['ch_date'] = this.chDate;
    data['remarks'] = this.remarks;
    data['msg'] = this.msg;
    data['flag'] = this.flag;
    return data;
  }
}
